travis:
  secure:
    BINSTAR_TOKEN: rz1ElG6fWNB0v8YINu33ifdbXc+J4O/sQNgprwg8fx0cfn0EbcecdgGMqAgsS6YUN7da64Dhln1ZyPIM3D8V84iSTlFrlg9/jFqKTr2MegARbjuwwxgyoKDAJnUsp8eM2dQQHDMJBshYcAlgdiwDcmDTyHTsX9ZJI1h8dSo/jE0mZt7aY6x3hsv8tr5RlAHp51D70gMcQJxsgrEhmeouiaKwvyDkv2a8zm+k+4/Gf2rXkDff0AloGHNWHVpwdGeejN6Tmhv5YbOsG6A9+2Tq7ew191yAacgLiOF41La/DQ1LhEko4MwED+S/Zp9OpXqErB652fj3EnOfY0DPTgG/e4nENbp/4htq+tChjAPLSfQHTs+77jet1e0jEv88yB5aA/Ge0/7nRV4r1YJw3lQH7eBTwV23nPhbUK0dbVsk7KXt3zjcGDhj8qgt6Y9VssEFkzEatVaJkAyYcEjdmn30onmHtMpd/USSUb9AHVB3ligeaD3DdX19iVZ7TcXFQ8ImqapJGUlTKG13Z8QQa5rh85MDA0E4+hm4tDXmFsBX0YjFHm1vU8fMgDDrtyuHGz8RzoOOF57bRu8aqGpxHnKdZQAQg5PgAh+b6Cq5nAs/0rGZoSzIsVvrJaTtWQ03ZYyPOayC5nwyHrDmTrn5VhjUkBAmPts19ak8yqq2Yefvb1c=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
